<?php

namespace ContainerKAz2Cx2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RXlGBNiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rXlGBNi' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rXlGBNi'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\HomeController::DetailProduit' => ['privates', '.service_locator.iGUm1r8', 'get_ServiceLocator_IGUm1r8Service', true],
            'App\\Controller\\HomeController::Pannier' => ['privates', '.service_locator.K6iplCK', 'get_ServiceLocator_K6iplCKService', true],
            'App\\Controller\\HomeController::add' => ['privates', '.service_locator.hetMHhQ', 'get_ServiceLocator_HetMHhQService', true],
            'App\\Controller\\HomeController::index' => ['privates', '.service_locator.ONtZwya', 'get_ServiceLocator_ONtZwyaService', true],
            'App\\Controller\\HomeController::remove' => ['privates', '.service_locator.hetMHhQ', 'get_ServiceLocator_HetMHhQService', true],
            'App\\Controller\\ProduitController::delete' => ['privates', '.service_locator.HkHf8J3', 'get_ServiceLocator_HkHf8J3Service', true],
            'App\\Controller\\ProduitController::edit' => ['privates', '.service_locator.HkHf8J3', 'get_ServiceLocator_HkHf8J3Service', true],
            'App\\Controller\\ProduitController::index' => ['privates', '.service_locator.ONtZwya', 'get_ServiceLocator_ONtZwyaService', true],
            'App\\Controller\\ProduitController::new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\ProduitController::show' => ['privates', '.service_locator.iGUm1r8', 'get_ServiceLocator_IGUm1r8Service', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.kXtg5m1', 'get_ServiceLocator_KXtg5m1Service', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\UserController::delete' => ['privates', '.service_locator.GPGtF8v', 'get_ServiceLocator_GPGtF8vService', true],
            'App\\Controller\\UserController::edit' => ['privates', '.service_locator.GPGtF8v', 'get_ServiceLocator_GPGtF8vService', true],
            'App\\Controller\\UserController::index' => ['privates', '.service_locator.Q1F27w5', 'get_ServiceLocator_Q1F27w5Service', true],
            'App\\Controller\\UserController::new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\UserController::show' => ['privates', '.service_locator.4T4EJFR', 'get_ServiceLocator_4T4EJFRService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'App\\Controller\\HomeController:DetailProduit' => ['privates', '.service_locator.iGUm1r8', 'get_ServiceLocator_IGUm1r8Service', true],
            'App\\Controller\\HomeController:Pannier' => ['privates', '.service_locator.K6iplCK', 'get_ServiceLocator_K6iplCKService', true],
            'App\\Controller\\HomeController:add' => ['privates', '.service_locator.hetMHhQ', 'get_ServiceLocator_HetMHhQService', true],
            'App\\Controller\\HomeController:index' => ['privates', '.service_locator.ONtZwya', 'get_ServiceLocator_ONtZwyaService', true],
            'App\\Controller\\HomeController:remove' => ['privates', '.service_locator.hetMHhQ', 'get_ServiceLocator_HetMHhQService', true],
            'App\\Controller\\ProduitController:delete' => ['privates', '.service_locator.HkHf8J3', 'get_ServiceLocator_HkHf8J3Service', true],
            'App\\Controller\\ProduitController:edit' => ['privates', '.service_locator.HkHf8J3', 'get_ServiceLocator_HkHf8J3Service', true],
            'App\\Controller\\ProduitController:index' => ['privates', '.service_locator.ONtZwya', 'get_ServiceLocator_ONtZwyaService', true],
            'App\\Controller\\ProduitController:new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\ProduitController:show' => ['privates', '.service_locator.iGUm1r8', 'get_ServiceLocator_IGUm1r8Service', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.kXtg5m1', 'get_ServiceLocator_KXtg5m1Service', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\UserController:delete' => ['privates', '.service_locator.GPGtF8v', 'get_ServiceLocator_GPGtF8vService', true],
            'App\\Controller\\UserController:edit' => ['privates', '.service_locator.GPGtF8v', 'get_ServiceLocator_GPGtF8vService', true],
            'App\\Controller\\UserController:index' => ['privates', '.service_locator.Q1F27w5', 'get_ServiceLocator_Q1F27w5Service', true],
            'App\\Controller\\UserController:new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\UserController:show' => ['privates', '.service_locator.4T4EJFR', 'get_ServiceLocator_4T4EJFRService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
        ], [
            'App\\Controller\\HomeController::DetailProduit' => '?',
            'App\\Controller\\HomeController::Pannier' => '?',
            'App\\Controller\\HomeController::add' => '?',
            'App\\Controller\\HomeController::index' => '?',
            'App\\Controller\\HomeController::remove' => '?',
            'App\\Controller\\ProduitController::delete' => '?',
            'App\\Controller\\ProduitController::edit' => '?',
            'App\\Controller\\ProduitController::index' => '?',
            'App\\Controller\\ProduitController::new' => '?',
            'App\\Controller\\ProduitController::show' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\UserController::delete' => '?',
            'App\\Controller\\UserController::edit' => '?',
            'App\\Controller\\UserController::index' => '?',
            'App\\Controller\\UserController::new' => '?',
            'App\\Controller\\UserController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\HomeController:DetailProduit' => '?',
            'App\\Controller\\HomeController:Pannier' => '?',
            'App\\Controller\\HomeController:add' => '?',
            'App\\Controller\\HomeController:index' => '?',
            'App\\Controller\\HomeController:remove' => '?',
            'App\\Controller\\ProduitController:delete' => '?',
            'App\\Controller\\ProduitController:edit' => '?',
            'App\\Controller\\ProduitController:index' => '?',
            'App\\Controller\\ProduitController:new' => '?',
            'App\\Controller\\ProduitController:show' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\UserController:delete' => '?',
            'App\\Controller\\UserController:edit' => '?',
            'App\\Controller\\UserController:index' => '?',
            'App\\Controller\\UserController:new' => '?',
            'App\\Controller\\UserController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
