<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKAz2Cx2\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKAz2Cx2/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKAz2Cx2.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKAz2Cx2\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKAz2Cx2\App_KernelDevDebugContainer([
    'container.build_hash' => 'KAz2Cx2',
    'container.build_id' => 'c5bde6dd',
    'container.build_time' => 1640208929,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKAz2Cx2');
